### ISSUE TITLE
Crash when editing third slot; inability to save url without setting interval and power

### ISSUE THREAD

**Issue by simonrob** [NordicSemiconductor/Android-nRF-Beacon-for-Eddystone#6]
Trying to save data to the third slot (slot 2) sometimes (but not always!) crashes with the following error:

```
Process: no.nordicsemi.android.nrfbeacon.nearby, PID: 4368
 java.lang.IndexOutOfBoundsException: Invalid index 2, size is 1
     at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
     at java.util.ArrayList.set(ArrayList.java:481)
     at no.nordicsemi.android.nrfbeacon.nearby.update.UpdateFragment.configureUrlSlot(UpdateFragment.java:1555)
     at no.nordicsemi.android.nrfbeacon.nearby.update.ReadWriteAdvertisementSlotDialogFragment$2.onClick(ReadWriteAdvertisementSlotDialogFragment.java:285)
     at android.view.View.performClick(View.java:5204)
     at android.view.View$PerformClick.run(View.java:21153)
     at android.os.Handler.handleCallback(Handler.java:739)
     at android.os.Handler.dispatchMessage(Handler.java:95)
     at android.os.Looper.loop(Looper.java:148)
     at android.app.ActivityThread.main(ActivityThread.java:5417)
     at java.lang.reflect.Method.invoke(Native Method)
     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

In addition, some beacons come with both interval and power set to zero in the second and third slots - currently, it is not possible to configure a URL in these slots before setting the interval and power (pressing configure has no effect - if this is a technical limitation, could it instead show a hint?).

**Comment by roshanrajaratnam** [comment]
Hi Simon,

I have never come across this scenario but configuring URL has been working
without any issues with the current version. I can look this up on Monday
and get back.

On 7 Oct 2016 5:54 pm, "Simon Robinson" <notifications@github.com> wrote:

Trying to save data to the third slot (slot 2) sometimes (but not always!)
crashes with the following error:

Process: no.nordicsemi.android.nrfbeacon.nearby, PID: 4368
 java.lang.IndexOutOfBoundsException: Invalid index 2, size is 1
     at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
     at java.util.ArrayList.set(ArrayList.java:481)
     at no.nordicsemi.android.nrfbeacon.nearby.update.UpdateFragment.configureUrlSlot(UpdateFragment.java:1555)
     at no.nordicsemi.android.nrfbeacon.nearby.update.ReadWriteAdvertisementSlotDialogFragment$2.onClick(ReadWriteAdvertisementSlotDialogFragment.java:285)
     at android.view.View.performClick(View.java:5204)
     at android.view.View$PerformClick.run(View.java:21153)
     at android.os.Handler.handleCallback(Handler.java:739)
     at android.os.Handler.dispatchMessage(Handler.java:95)
     at android.os.Looper.loop(Looper.java:148)
     at android.app.ActivityThread.main(ActivityThread.java:5417)
     at java.lang.reflect.Method.invoke(Native Method)
     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

In addition, some beacons come with both interval and power set to zero in
the second and third slots - currently, it is not possible to configure a
URL in these slots before setting the interval and power (pressing
configure has no effect - if this is a technical limitation, could it
instead show a hint?).

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/NordicSemiconductor/Android-nRF-Beacon-for-Eddystone/issues/6>,
or mute the thread

**Comment by roshanrajaratnam** [comment]
@simonrob are you able to reproduce this error? I'm unable to reproduce it on my end. If possible could you please send me the steps to reproduce? Thanks

**Comment by simonrob** [comment]
@roshanrajaratnam - yes, but on closer inspection it may be related to the prefix selector rather than the configuration of the third slot. It also happens for slot 1 as well as slot 2.

The simplest way I can find to reproduce it is to connect to a beacon that already has three slots configured as URLs, switch to slot 2, then use the prefix selector to change from, e.g., https://www. to https:// - pressing configure causes this crash every time for me.

Let me know if you need any more information.

**Comment by roshanrajaratnam** [comment]
Great thanks for the input, i've tried the same steps as you have mentioned, but I am still unable to reproduce the error on my end. Are you using the latest version of the app (V2.2)?

**Comment by simonrob** [comment]
Yes - it's the latest version of the app. And you're right about the prefix (sometimes changing the URL text crashes the app too). The key step seems to be changing slots then trying to update the URL.

Could it be beacon related somehow? (I'm using one of these: https://fccid.io/pdf.php?id=2968851)

**Comment by roshanrajaratnam** [comment]
That would be my guess as well because the steps don't seem to reproduce for me. I wonder if this beacon supports the eddystone firmware? Have you flashed the beacon with the Eddystone firmware?

**Comment by simonrob** [comment]
It's one of the Eddystone beacons given out by the Physical Web team so I'd have thought it would already have that firmware (when the app doesn't crash, the beacon does function normally with all slots and data types etc).

Happy to try updating the firmware if you can point me towards where to get the firmware and basic instructions though.

**Comment by roshanrajaratnam** [comment]
Right. Perhaps you could also try viewing the broadcast capabilities of this beacon on the update tab and send a screenshot please? The app should ideally work with the standard Eddystone Gatt Configuration Service Spec.

**Comment by simonrob** [comment]
Here's the broadcast capabilities page. Interestingly, the slot information (also below) shows that only slot 0 is configured - this is not the case (all three slots are configured and broadcasting). On a possibly related note, I haven't ever seen the beacon in the nRF app's beacons tab, though it does show up in Android's Nearby discoveries app.

![broadcast-capabilities](https://cloud.githubusercontent.com/assets/934006/19236791/262ff9a2-8ef1-11e6-96bd-99250f320d63.png)
![slot-information](https://cloud.githubusercontent.com/assets/934006/19236795/297eb83c-8ef1-11e6-8000-a2f198971bf4.png)

**Comment by roshanrajaratnam** [comment]
This is interesting. I think this seems to be something to do with the beacon firmware itself. All these features are fully functional on my end. However the beacons tab will only display, UID and EID beacons that are registered on the proximity API. In addition , for this to work you will have to compile the source code with your own API key by enabling the nearby api. The reason being you need write permissions to register the beacons hence it will not show up on your beacons tab.

**Comment by simonrob** [comment]
Ah, ok - looks like it might be best for me to wait for things to become a little more established/settled then. Feel free to close this issue - the problem is only intermittent, and seems to be beacon rather than app-related. Thanks for the help!

**Comment by roshanrajaratnam** [comment]
No problem! Please do let me know if you need any more information. I will keep you posted for new updates on our end!
